### ISSUE TITLE
Citation to TLRU

### ISSUE THREAD

**Issue by mbilal084** [tinovyatkin/tlru#539]
Thank you for implementing the TLRU scheme. It is always better to give credit to those who first publish an idea. We are the first who come up with this idea and published a research article. Please cite the following article in your about section. Thank you.
M. Bilal and S. Kang, "Time Aware Least Recent Used (TLRU) cache management policy in ICN," 16th International Conference on Advanced Communication Technology, 2014, pp. 528-532, doi: 10.1109/ICACT.2014.6779016.

**Comment by tinovyatkin** [comment]
I never heard about you or read your work before publishing this library so I'm surprised that you started bombed myself with request to cite a work I'm unfamiliar with (and it seems you have enough time to do the same[ with everybody](https://github.com/kgriffs/tlru#related-works)). 
I'm sorry, but I think your publication is unrelated and doubt your are inventor or owner of that word or a patent for this algorithm.
If otherwise not required by a law I will keep ignoring your attempts.

**Comment by mbilal084** [comment]
You are using the same terminology and exact same algorithm I published in 2014. The other repository owner talked to me and after explanation I found there is an innovation from his side as well, but in your case, it's totally the same scheme I published back in 2014. Will you share the link where did you get this idea? Perhaps Wikipedia? 
Anyways I will try to contact the IEEE copyright department to resolve the issue.
